/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "alarm.h"
#include "clock.h"
#include "menu.h"
#include "heading.h"

#define col_gui GUI_BLACK

extern uint8_t auc[500];
extern volatile int sec;
extern volatile int sec2;

uint8_t month, day, dow, hours, minutes, seconds, weekday;
WM_HWIN hWinalarm;

static GUI_CONST_STORAGE GUI_COLOR _Colorsdown[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Paldown = {
  2,  // Number of entries
  1,  // Has transparency
  &_Colorsdown[0]
};

static GUI_CONST_STORAGE unsigned char _acdown[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ______XX, XX______, ________, ________, ________, ________, __XXXX__, ________,
  ____XXXX, XXX_____, ________, ________, ________, ________, _XXXXXXX, ________,
  ___XXXXX, XXXX____, ________, ________, ________, ________, XXXXXXXX, X_______,
  __XXXXXX, XXXXX___, ________, ________, ________, _______X, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXX__, ________, ________, ________, ______XX, XXXXXXXX, XXX_____,
  _XXXXXXX, XXXXXXX_, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ____XXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, ___XXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, __XXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____,
  _XXXXXXX, XXXXXXXX, XXXX____, ________, ________, XXXXXXXX, XXXXXXXX, XXX_____,
  __XXXXXX, XXXXXXXX, XXXXX___, ________, _______X, XXXXXXXX, XXXXXXXX, XX______,
  ___XXXXX, XXXXXXXX, XXXXXX__, ________, ______XX, XXXXXXXX, XXXXXXXX, X_______,
  ____XXXX, XXXXXXXX, XXXXXXX_, ________, _____XXX, XXXXXXXX, XXXXXXXX, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXXXXX, XXXXXXX_, ________,
  ______XX, XXXXXXXX, XXXXXXXX, X_______, ___XXXXX, XXXXXXXX, XXXXXX__, ________,
  _______X, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, XXXXXXXX, XXXXX___, ________,
  ________, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________,
  ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________,
  ________, ________, _____XXX, XXXXXXXX, XXXXXXX_, ________, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXX__, ________, ________, ________,
  ________, ________, _______X, XXXXXXXX, XXXXX___, ________, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXX____, ________, ________, ________,
  ________, ________, ________, _XXXXXXX, XXX_____, ________, ________, ________,
  ________, ________, ________, __XXXXXX, XX______, ________, ________, ________,
  ________, ________, ________, ___XXXXX, X_______, ________, ________, ________,
  ________, ________, ________, ____XXXX, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmdown = {
  60, // xSize
  60, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acdown,  // Pointer to picture data (indices)
  &_Paldown   // Pointer to palette
};

static GUI_CONST_STORAGE GUI_COLOR _Colorsup[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palup = {
  2,  // Number of entries
  1,  // Has transparency
  &_Colorsup[0]
};

static GUI_CONST_STORAGE unsigned char _acup[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ____XXXX, ________, ________, ________, ________,
  ________, ________, ________, ___XXXXX, X_______, ________, ________, ________,
  ________, ________, ________, __XXXXXX, XX______, ________, ________, ________,
  ________, ________, ________, _XXXXXXX, XXX_____, ________, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXX____, ________, ________, ________,
  ________, ________, _______X, XXXXXXXX, XXXXX___, ________, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXX__, ________, ________, ________,
  ________, ________, _____XXX, XXXXXXXX, XXXXXXX_, ________, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________,
  ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXX____, ________,
  _______X, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, XXXXXXXX, XXXXX___, ________,
  ______XX, XXXXXXXX, XXXXXXXX, X_______, ___XXXXX, XXXXXXXX, XXXXXX__, ________,
  _____XXX, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXXXXX, XXXXXXX_, ________,
  ____XXXX, XXXXXXXX, XXXXXXX_, ________, _____XXX, XXXXXXXX, XXXXXXXX, ________,
  ___XXXXX, XXXXXXXX, XXXXXX__, ________, ______XX, XXXXXXXX, XXXXXXXX, X_______,
  __XXXXXX, XXXXXXXX, XXXXX___, ________, _______X, XXXXXXXX, XXXXXXXX, XX______,
  _XXXXXXX, XXXXXXXX, XXXX____, ________, ________, XXXXXXXX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, _XXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, __XXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, ___XXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ____XXXX, XXXXXXXX, XXXX____,
  _XXXXXXX, XXXXXXX_, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____,
  _XXXXXXX, XXXXXX__, ________, ________, ________, ______XX, XXXXXXXX, XXX_____,
  __XXXXXX, XXXXX___, ________, ________, ________, _______X, XXXXXXXX, XX______,
  ___XXXXX, XXXX____, ________, ________, ________, ________, XXXXXXXX, X_______,
  ____XXXX, XXX_____, ________, ________, ________, ________, _XXXXXXX, ________,
  ______XX, XX______, ________, ________, ________, ________, __XXXX__, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmup = {
  60, // xSize
  60, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acup,  // Pointer to picture data (indices)
  &_Palup   // Pointer to palette
};


static const GUI_WIDGET_CREATE_INFO _aDialogCreate3[] = {
  { WINDOW_CreateIndirect, "Alarm", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_0, 10, 90, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_1, 10, 151, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_2, 248, 90, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_3, 248, 151, 60, 50, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "", ID_CHECKBOX_0, 137, 194, 86, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_0, 82, 107, 70, 80, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_1, 163, 107, 70, 80, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ALARM", ID_TEXT_2, 76, 50, 184, 35, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_3, 13, 50, 293, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

static int _Skinup(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
  int Index, xSize, ySize, IsPressed;
  WM_HWIN hWin;
  const GUI_BITMAP * pBm;
  GUI_COLOR Color;

  hWin = pDrawItemInfo->hWin;
  switch (pDrawItemInfo->Cmd)
  {
	  case WIDGET_ITEM_DRAW_BACKGROUND:
	  {
			  IsPressed = BUTTON_IsPressed(pDrawItemInfo->hWin);
			  if (IsPressed)
			  {
				  Color = GUI_BLUE | 0x10000000;
				  GUI_SetBkColor(Color);
				  GUI_Clear();
			  }
			  	  GUI_DrawBitmap(&bmup, 0,0);
		break;
	  }
  }
  return 0;
}
static int _Skindown(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
  int Index, xSize, ySize, IsPressed;
  WM_HWIN hWin;
  const GUI_BITMAP * pBm;
  GUI_COLOR Color;

  hWin = pDrawItemInfo->hWin;
  switch (pDrawItemInfo->Cmd)
  {
	  case WIDGET_ITEM_DRAW_BACKGROUND:
	  {
			  IsPressed = BUTTON_IsPressed(pDrawItemInfo->hWin);
			  if (IsPressed)
			  {
				  Color = GUI_BLUE | 0x10000000;
				  GUI_SetBkColor(Color);
				  GUI_Clear();
			  }
			  	  GUI_DrawBitmap(&bmdown, 0,0);
		break;
	  }
  }
  return 0;
}

static void _cbDialog_alarm(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  char number[2];
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId)
  {
  case WM_PAINT:
  {
  	  taskENTER_CRITICAL();
  	  AB0805_getDateTime24(0, &month, &day, &hours, &minutes, &seconds);
  	  weekday=AB0805_getDayOfWeek();
  	  taskEXIT_CRITICAL();

  	  if(hours>=6 && hours<20)
  	  {
  		  taskENTER_CRITICAL();
  		  LCD_BMP("0:dzien.bmp");
  		  taskEXIT_CRITICAL();
  	  }
  	  else
  	  {
  		  taskENTER_CRITICAL();
  		  LCD_BMP("0:noc.bmp");
  		  taskEXIT_CRITICAL();
  	  }
  	  break;
    }
  case WM_INIT_DIALOG:
  {
	  taskENTER_CRITICAL();
	  AB0805_getDateTime24(0, &month, &day, &hours, &minutes, &seconds);
	  taskEXIT_CRITICAL();

	hItem = pMsg->hWin;
	WINDOW_SetBkColor(hItem, GUI_TRANSPARENT);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	BUTTON_SetSkin(hItem, _Skinup);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
	BUTTON_SetSkin(hItem, _Skinup);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	BUTTON_SetSkin(hItem, _Skindown);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
	BUTTON_SetSkin(hItem, _Skindown);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontD36x48);
    sprintf(number,"%0.2d",hours);
	TEXT_SetText(hItem,number);
	TEXT_SetTextColor(hItem,col_gui);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontD36x48);
    sprintf(number,"%0.2d",minutes);
	TEXT_SetText(hItem,number);
	TEXT_SetTextColor(hItem,col_gui);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_Font32B_1);
    TEXT_SetText(hItem, "ALARM");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

    break;
  }
  case WM_NOTIFY_PARENT:

    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id)
    {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode)
      {
		  case WM_NOTIFICATION_CLICKED:
		  {
			  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
			  TEXT_GetText(hItem,auc,500);
			  int k=atoi(auc);
			  k++;
			  sprintf(number,"%0.2d",k);
			  TEXT_SetText(hItem,number);
			  break;
		  }
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:

		  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		  TEXT_GetText(hItem,auc,500);
		  int k=atoi(auc);
		  k--;
		  sprintf(number,"%0.2d",k);
		  TEXT_SetText(hItem,number);

        break;
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
		  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		  TEXT_GetText(hItem,auc,500);
		  int k=atoi(auc);
		  k++;
		  sprintf(number,"%0.2d",k);
		  TEXT_SetText(hItem,number);
        break;
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
		  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		  TEXT_GetText(hItem,auc,500);
		  int k=atoi(auc);
		  k--;
		  sprintf(number,"%0.2d",k);
		  TEXT_SetText(hItem,number);
        break;
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode)
      {
      case WM_NOTIFICATION_VALUE_CHANGED:
      {

    	    AB0805_writeByte(0xD2, 0x18, 0b00010000);
    	    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
  		  	TEXT_GetText(hItem,auc,500);
    	    AB0805_setHours24_Alarm(atoi(auc));
    	    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    	    TEXT_GetText(hItem,auc,500);
    	    AB0805_setMinutes_Alarm(atoi(auc));
    	    AB0805_setSeconds_Alarm(00);
      }

        break;
      }
      break;
   }
    break;

  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

WM_HWIN CreateAlarm(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate3, GUI_COUNTOF(_aDialogCreate3), _cbDialog_alarm, WM_HBKWIN, 0, 0);
  return hWin;
}

void Alarm( void * pvParameters)
{

	hWinalarm  = CreateAlarm();
	if(Menu_Handle!=NULL)vTaskDelete(Menu_Handle);
	Menu_Handle=NULL;

	while(1)
	{
		vTaskDelay(100);
		GUI_Exec();
	}
}
