/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "counter.h"
#include "clock.h"
#include "menu.h"
#include "heading.h"

extern volatile int sec;
extern volatile int sec2;


static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
		  { FRAMEWIN_CreateIndirect, "counter", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x0, 0 },
		  { TEXT_CreateIndirect, "big", ID_TEXT_0, 18, 24, 118, 93, 0, 0x64, 0 },
		  { TEXT_CreateIndirect, "jedn", ID_TEXT_1, 150, 71, 32, 33, 0, 0x64, 0 },
		  { TEXT_CreateIndirect, "label", ID_TEXT_2, 23, 174, 39, 17, 0, 0x64, 0 },
		  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 17, 202, 200, 100, 0, 0x0, 0 },
		  { TEXT_CreateIndirect, "max_v", ID_TEXT_3, 73, 172, 140, 20, 0, 0x64, 0 },
		  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 21, 145, 80, 20, 0, 0x64, 0 },
		  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 74, 143, 80, 20, 0, 0x64, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/


static GRAPH_DATA_Handle  _ahData; // Array of handles for the GRAPH_DATA objects
static GRAPH_SCALE_Handle _hScaleV;   // Handle of vertical scale
static GRAPH_SCALE_Handle _hScaleH;   // Handle of horizontal scale
static I16 _aValue[30];



static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'counter'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleVis(hItem, 0);
    //
    // Initialization of 'big'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_D80);
    TEXT_SetText(hItem, "54");
    //
    // Initialization of 'jedn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "5");
    TEXT_SetFont(hItem, GUI_FONT_D32);
    //
    // Initialization of 'label'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    TEXT_SetText(hItem, "MAX");
    //
    // Initialization of 'max_v'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem, "63.4");
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "AVS");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_24B_1);
    TEXT_SetText(hItem, "20.2");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);


	GRAPH_SetGridDistY(hItem, 10);
	GRAPH_SetGridVis(hItem, 1);
	GRAPH_SetGridFixedX(hItem, 1);


	_hScaleV = GRAPH_SCALE_Create( 5, GUI_TA_RIGHT, GRAPH_SCALE_CF_VERTICAL, 100);
	GRAPH_SCALE_SetTextColor(_hScaleV, GUI_GREEN);
	GRAPH_AttachScale(hItem, _hScaleV);
	//
	// Create and add horizontal scale
	//
	_hScaleH = GRAPH_SCALE_Create(5, GUI_TA_CENTER, GRAPH_SCALE_CF_HORIZONTAL, 50);
	GRAPH_SCALE_SetTextColor(_hScaleH, GUI_BLUE);
	GRAPH_AttachScale(hItem, _hScaleH);

	  _ahData = GRAPH_DATA_YT_Create(GUI_BLUE, 500 , mem, 100);
	   GRAPH_AttachData(hItem, _ahData);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createcounter
*/

WM_HWIN Createcounter(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0 , 0);
  return hWin;
}


void Counter( void * pvParameters)
{
	WM_HWIN hWincounter;
	hWincounter  = Createcounter();
	if(Menu_Handle!=NULL)vTaskDelete(Menu_Handle);
	if(Heading_Handle!=NULL)vTaskDelete(Heading_Handle);
//	GUI_SetOrientation(0);
	int i=0;

	WM_HWIN hGraph;

	hGraph=WM_GetDialogItem(hWincounter, ID_GRAPH_0);
	_ahData = GRAPH_DATA_YT_Create(GUI_BLUE, 500 , 0, 0);
	GRAPH_AttachData(hGraph, _ahData);

	while(1)
	{
		if(GUI_PID_IsPressed())
		{
			if(sec2>1000)
			{
				xTaskCreate(Menu,(char const*)"Menu",512,NULL,6,&Menu_Handle);
				xTaskCreate(Heading_Task,(char const*)"Heading",512,NULL, 6, &Heading_Handle);
			}
		}else
		{
			sec2=0;
		}

		if(vol_up)
		{
			  while(1){CPU_OFF;}
		}
		else
		{
			  CPU_ON;
		}

		WM_HWIN hText = WM_GetDialogItem(hWincounter, ID_TEXT_0);
		TEXT_SetText(hText,itoa(i,t,10));
		i++;
		vTaskDelay(100);
		WM_Paint(hWincounter);

		for (int i = 0; i<10; i++)
		{
		  _aValue[i] = get_random(0,100);

		}
			GRAPH_DATA_YT_AddValue(_ahData, _aValue[0]);
//			backlight(SLIDER_GetValue(hSlider));

	}
}
