/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Math64.c                                              *
* Font:        Cambria Math                                          *
* Height:      64                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  64                                           *
* Character disabled:  0x40 (64)                                     *
* Character disabled:  0x50 (80)                                     *
* Character enabled:   0x50 (80)                                     *
* Character disabled:  0x50 (80)                                     *
* Character disabled:  0x60 (96)                                     *
* Character disabled:  0xC0 (192)                                    *
* Range disabled:       0000 - FFFF                                  *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3B (59)                                     *
* Character disabled:  0x3A (58)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3F (63)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMath64;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontMath64_0030[ 21] = { /* code 0030, DIGIT ZERO */
  0x3F, 0xFF, 0x50,
  0xBF, 0xCF, 0xE0,
  0xEF, 0x4F, 0xF2,
  0xFF, 0x2F, 0xF2,
  0xEF, 0x4F, 0xF2,
  0xBF, 0xCF, 0xD0,
  0x3F, 0xFF, 0x50
};

GUI_CONST_STORAGE unsigned char acGUI_FontMath64_0031[ 28] = { /* code 0031, DIGIT ONE */
  0x04, 0xFE, 0x20, 0x00,
  0x7D, 0xFF, 0x20, 0x00,
  0x00, 0xFF, 0x20, 0x00,
  0x00, 0xFF, 0x20, 0x00,
  0x00, 0xFF, 0x20, 0x00,
  0x00, 0xFF, 0x30, 0x00,
  0xBF, 0xFF, 0xFD, 0x10
};

GUI_CONST_STORAGE unsigned char acGUI_FontMath64_0032[ 21] = { /* code 0032, DIGIT TWO */
  0x5F, 0xFF, 0x90,
  0xFF, 0x8F, 0xF2,
  0x00, 0x1F, 0xF1,
  0x00, 0x9F, 0x60,
  0x07, 0xE7, 0x00,
  0x5C, 0x7E, 0xF2,
  0xEF, 0xFF, 0xF2
};

GUI_CONST_STORAGE unsigned char acGUI_FontMath64_0033[ 21] = { /* code 0033, DIGIT THREE */
  0x5F, 0xFF, 0xA0,
  0xFF, 0x7F, 0xF2,
  0x01, 0x7F, 0x90,
  0x0F, 0xFF, 0x60,
  0x00, 0x4F, 0xF1,
  0xFF, 0x7F, 0xF1,
  0x7F, 0xFF, 0x60
};

GUI_CONST_STORAGE unsigned char acGUI_FontMath64_0034[ 28] = { /* code 0034, DIGIT FOUR */
  0x00, 0x3F, 0xF2, 0x00,
  0x01, 0xBF, 0xF2, 0x00,
  0x09, 0xBF, 0xF2, 0x00,
  0x7A, 0x4F, 0xF2, 0x00,
  0xFF, 0xFF, 0xFF, 0x20,
  0x00, 0x0F, 0xF2, 0x00,
  0x00, 0x8F, 0xFA, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMath64_0035[ 21] = { /* code 0035, DIGIT FIVE */
  0xFF, 0xFF, 0xF0,
  0xFF, 0x40, 0x00,
  0xFF, 0x40, 0x00,
  0xDF, 0xFF, 0x90,
  0x00, 0x3F, 0xF1,
  0xFF, 0x8F, 0xF1,
  0xBF, 0xFF, 0x70
};

GUI_CONST_STORAGE unsigned char acGUI_FontMath64_0036[ 28] = { /* code 0036, DIGIT SIX */
  0x02, 0xCF, 0xE0, 0x00,
  0x2F, 0xF7, 0x10, 0x00,
  0xAF, 0x90, 0x00, 0x00,
  0xEF, 0xFF, 0xF8, 0x00,
  0xFF, 0x33, 0xFF, 0x20,
  0xCF, 0x73, 0xFF, 0x10,
  0x3F, 0xFF, 0xF6, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMath64_0037[ 21] = { /* code 0037, DIGIT SEVEN */
  0xFF, 0xFF, 0xE0,
  0xFF, 0x4C, 0xA0,
  0x00, 0x8E, 0x50,
  0x00, 0xEF, 0x10,
  0x05, 0xFB, 0x00,
  0x0B, 0xF7, 0x00,
  0x0F, 0xF2, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMath64_0038[ 28] = { /* code 0038, DIGIT EIGHT */
  0x4F, 0xFF, 0xF7, 0x00,
  0xEF, 0x63, 0xFF, 0x20,
  0xDF, 0x73, 0xFE, 0x10,
  0x3F, 0xFF, 0xF5, 0x00,
  0xCF, 0x64, 0xFF, 0x10,
  0xFF, 0x63, 0xFF, 0x10,
  0x5F, 0xFF, 0xF6, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMath64_0039[ 21] = { /* code 0039, DIGIT NINE */
  0x5F, 0xFF, 0x60,
  0xEF, 0x8F, 0xF1,
  0xFF, 0x5F, 0xF2,
  0x8F, 0xFF, 0xF2,
  0x00, 0x3F, 0xF0,
  0x01, 0xDF, 0x80,
  0x0E, 0xF8, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontMath64_CharInfo[10] = {
   {   6,   7,   1,  29,   7, acGUI_FontMath64_0030 } /* code 0030, DIGIT ZERO */
  ,{   7,   7,   1,  29,   7, acGUI_FontMath64_0031 } /* code 0031, DIGIT ONE */
  ,{   6,   7,   1,  29,   7, acGUI_FontMath64_0032 } /* code 0032, DIGIT TWO */
  ,{   6,   7,   1,  29,   7, acGUI_FontMath64_0033 } /* code 0033, DIGIT THREE */
  ,{   7,   7,   0,  29,   7, acGUI_FontMath64_0034 } /* code 0034, DIGIT FOUR */
  ,{   6,   7,   1,  29,   7, acGUI_FontMath64_0035 } /* code 0035, DIGIT FIVE */
  ,{   7,   7,   1,  29,   7, acGUI_FontMath64_0036 } /* code 0036, DIGIT SIX */
  ,{   5,   7,   1,  29,   7, acGUI_FontMath64_0037 } /* code 0037, DIGIT SEVEN */
  ,{   7,   7,   1,  29,   7, acGUI_FontMath64_0038 } /* code 0038, DIGIT EIGHT */
  ,{   6,   7,   1,  29,   7, acGUI_FontMath64_0039 } /* code 0039, DIGIT NINE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMath64_Prop1 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontMath64_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMath64 = {
   GUI_FONTTYPE_PROP_AA4_EXT /* type of font    */
  ,64 /* height of font  */
  ,64 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMath64_Prop1}
  ,36 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,7 /* Height of capital characters */
};

