/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "mp3.h"


char name[107];//__attribute((section(".ExRam")));
u8 rand[250];//__attribute((section(".ExRam")));
u8 buffez[1024];//__attribute((section(".ExRam")));


static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
		  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
		  { BUTTON_CreateIndirect, "<<<<", ID_BUTTON_0, 27, 135, 80, 45, 0, 0x0, 0 },
		  { BUTTON_CreateIndirect, ">>>>", ID_BUTTON_1, 217, 135, 80, 41, 0, 0x0, 0 },
		  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 32, 95, 263, 20, 0, 0x0, 0 },
		  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 32, 70, 260, 20, 0, 0x0, 0 },
		  { TEXT_CreateIndirect, " MP3 Player", ID_TEXT_1, 32, 40, 259, 20, 0, 0x0, 0 },
		  { BUTTON_CreateIndirect, "play", ID_BUTTON_2, 122, 135, 80, 37, 0, 0x0, 0 },
		  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 171, 200, 119, 32, 0, 0x0, 0 },
		  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 28, 200, 112, 34, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{

	  WM_HWIN hItem;
	  int     NCode;
	  int     Id;
	  // USER START (Optionally insert additional variables)
	  // USER END

	  switch (pMsg->MsgId)
	  {
	  case WM_INIT_DIALOG:


	  	  taskENTER_CRITICAL();
	  	  LCD_BMP("0:dzien.bmp");
	  	  taskEXIT_CRITICAL();
	    //
	    // Initialization of 'Text'
	    //
	    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	    TEXT_SetFont(hItem, GUI_FONT_COMIC18B_ASCII);
	    TEXT_SetTextColor(hItem, 0x00FFFFFF);
	    //
	    // Initialization of ' MP3 Player'
	    //
	    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	    TEXT_SetFont(hItem, GUI_FONT_COMIC24B_ASCII);
	    TEXT_SetTextColor(hItem, 0x000000FF);
	    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	    // USER START (Optionally insert additional code for further widget initialization)
	    // USER END
	    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
	    SLIDER_SetValue(hItem,0x4a);
	    break;
	  case WM_NOTIFY_PARENT:
	    Id    = WM_GetId(pMsg->hWinSrc);
	    NCode = pMsg->Data.v;
	    switch(Id)
	    {
			case ID_BUTTON_0:
			{
			  switch(NCode)
			  {
			    case WM_NOTIFICATION_CLICKED:

				break;
			  }
			  break;
			}

			case ID_BUTTON_1:
			{
			  switch(NCode)
			  {
			  case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			  }
			  break;
			}

			case ID_BUTTON_2:
			{// Notifications sent by 'play'
			  switch(NCode)
			  {
			  case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			  }
			  break;
			}
			case ID_SLIDER_0:
			{// Notifications sent by 'Slider'
			  switch(NCode)
			  {

			  case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			  // USER START (Optionally insert additional code for further notification handling)
			  // USER END
			  }
			  break;
			}
	    // USER START (Optionally insert additional code for further Ids)
	    // USER END
	    }
	    break;
	    case WM_PAINT:
	    {
	  	  taskENTER_CRITICAL();
	  	  LCD_BMP("0:dzien.bmp");
	  	  taskEXIT_CRITICAL();
	    	break;
	    }
	  default:
	    WM_DefaultProc(pMsg);
	    break;
	  }
}


/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN CreateWindow(void)
{
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END
void MP3_player(void *pvParameters)
{
	u16 br=0;
	u8 fin=1;
	u8 play=0;
	u8 rd=0;
	FRESULT f;
	int size=0,co=0,vol=0x4a,on=1;
	int next=0;
	FIL fsrc;
	DIR dir;
	FATFS fs;
	FILINFO fno;

//	vTaskDelay(10);

	taskENTER_CRITICAL();

	f=f_mount(&fs,"",0);
	f=f_opendir(&dir,"0:music");

	fno.lfname = lfname;
	fno.lfsize = _MAX_LFN;

	while(!f_readdir(&dir, &fno) && fno.fname[0])
	{
		co++;
	}
	rd=co;

	while(rd--)
	{
		int k=get_random(0,co);

		for(int j=0;j<co-1;j++)
		{
			if(k==rand[j])br=1;
		}
		if(br==0)rand[rd]=k;
		else
		{
			br=0;
			rd++;
		}
	}

	br=0;
	rd=0;

	taskEXIT_CRITICAL();

	GUI_SetFont(GUI_FONT_COMIC18B_ASCII);
	WM_HWIN hWin=CreateWindow();
	WM_HWIN hText,hText1;
	WM_HWIN hSlider;
	WM_HWIN hProgBar;
	WM_HWIN hButton,hButton1,hButton2;

	name[0]='m';
	name[1]='u';
	name[2]='s';
	name[3]='i';
	name[4]='c';
	name[5]='/';

	if(Menu_Handle!=NULL)vTaskDelete(Menu_Handle);
	Menu_Handle=NULL;

	while(1)
	{


//		hText1 = WM_GetDialogItem(hWin, ID_TEXT_1);
		hText = WM_GetDialogItem(hWin, ID_TEXT_0);
		hSlider = WM_GetDialogItem(hWin, ID_SLIDER_0);
//		hSlider1 = WM_GetDialogItem(hWin, ID_SLIDER_1);
		hProgBar = WM_GetDialogItem(hWin, ID_PROGBAR_0);
		hButton = WM_GetDialogItem(hWin, ID_BUTTON_0);
		hButton1 = WM_GetDialogItem(hWin, ID_BUTTON_1);
		hButton2 = WM_GetDialogItem(hWin, ID_BUTTON_2);

		if(play==1)
		{
			SCI_ChipSelect(RESET);
			taskENTER_CRITICAL();
			f=f_read(&fsrc, buffez, sizeof(buffez), &br);

			   if(f == 0)
			   {
				   vol=SLIDER_GetValue(hSlider);

				   SDI_ChipSelect(SET);
				   for (int i=0;i<br;i++)
				   {
						 SPIPutChar(buffez[i]);
						 while(DREQ);
				   }
				   SDI_ChipSelect(RESET);
				   Mp3SetVolume(vol, vol);

				   if(br<sizeof(buffez))
				   {
					   fin=1;
				   }
			   }
			   Mp3SoftReset();

			 int dec1=size/(VS1003_GetBitrate()*1000/8);
			 u16 dec=Mp3ReadRegister(SPI_DECODE_TIME);
			 PROGBAR_SetValue(hProgBar, dec*100/dec1 );
			 taskEXIT_CRITICAL();
		}

		if(vol_up)
		{
			while(vol_up){};
			if(on==1)
			{
				GPIOB->BSRRL|=GPIO_BSRR_BS_9;
//				vTaskSuspend(TouchScreenTimer);
				on=0;
			}
			else
			{
				GPIOB->BSRRH|=GPIO_BSRR_BS_9;
//				vTaskResume(TouchScreenTimer);
//				LCD_init();
				on=1;
			}

	    }

		if(BUTTON_IsPressed(hButton))
		{
			while(BUTTON_IsPressed(hButton)){};
			fin=1;
		}
		if(BUTTON_IsPressed(hButton2))
		{
			while(BUTTON_IsPressed(hButton2)){};
			if(play==1)play=0;
			else play=1;
		}
		if(BUTTON_IsPressed(hButton1))
		{
			while(BUTTON_IsPressed(hButton1)){};
			fin=1;
			next-=2;
//			vTraceStart();
		}
//

		if(fin==1)
		{

			taskENTER_CRITICAL();

			next++;

			if(next==co)
			{
				next=0;
			}
//
				fno.lfname = lfname;
				fno.lfsize = _MAX_LFN;

				for(u8 k=6;k<106;k++)
				{
					name[k]=0;
				}


				f_opendir(&dir,"0:music");

				rd=0;

				while(rd!=rand[next])
				{
					f_readdir(&dir, &fno);
					rd++;
				}



				if(!f_readdir(&dir, &fno) && fno.fname[0])
				{
					taskEXIT_CRITICAL();
					int b=sizeof(fno.fname);
					int h=6;

					if(*fno.lfname!=0)
					{
						while(*fno.lfname != 0)
						{
							name[h]=*fno.lfname;
							fno.lfname++;
							h++;
						}
					}
					else
					{
						for(int j=6;j<b+6;j++)
						{
							name[j]=fno.fname[j-6];
						}
					}
				}

			Mp3Reset();
			taskENTER_CRITICAL();
			f_open(&fsrc,name,FA_READ | FA_OPEN_EXISTING);
			size=f_size(&fsrc);
			taskEXIT_CRITICAL();
//
			TEXT_SetText(hText,&name[6]);
			fin=0;

//			vTaskDelay(500);
//			vTaskResume(Heading_Handle);
		}


		vTaskDelay(200);
	}

}
