/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "clock.h"
#include "menu.h"
#include "heading.h"
#include "global_inc.h"
#include "ICONVIEW.h"

#define col_gui GUI_BLACK

extern volatile int sec;
extern volatile int sec2;
extern volatile uint8_t update;
extern volatile char received_string[12];
int kk=0;
u8 jed=1;
uint8_t auc[500];//__attribute((section(".ExRam")));
extern const GUI_FONT GUI_FontSolidEdgeStencil118;
extern const GUI_FONT GUI_FontStencil118;
uint8_t month, day, dow, hours, minutes, seconds, weekday;
WM_HWIN hWinclock;


static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
  { WINDOW_CreateIndirect, "clock", ID_WINDOW_0, 0, 0, 320, 240, WM_CF_SHOW, 0x0, 0},
  { TEXT_CreateIndirect, "hours", ID_TEXT_0, 43, 70, 120, 120, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "minutes", ID_TEXT_1, 178, 70, 120, 120, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 150, 50, 15, 120, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "weekday", ID_TEXT_3, 35, 35, 129, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "date", ID_TEXT_4, 175, 35, 40, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "month", ID_TEXT_7, 210, 35, 40, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "seconds", ID_TEXT_5, 200, 220, 37, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "till", ID_TEXT_6, 80, 200, 120, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "lesson", ID_TEXT_8, 150, 200, 120, 50, 0, 0x0, 0 },
};

static const GUI_WIDGET_CREATE_INFO _aDialogCreate2[] = {
  { WINDOW_CreateIndirect, "plan", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dzien", ID_TEXT_0, 51, 2, 222, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "plan", ID_TEXT_1, 22, 21, 276, 190, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "od", ID_TEXT_2, 59, 220, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "do", ID_TEXT_3, 208, 220, 80, 23, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "OD", ID_TEXT_4, 18, 220, 31, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "DO", ID_TEXT_5, 168, 220, 30, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};


static void _cbDialog(WM_MESSAGE * pMsg)
{
  WM_HWIN hItem;

  switch (pMsg->MsgId)
  {
  case WM_PAINT:
  {
//	  taskENTER_CRITICAL();
//	  AB0805_getDateTime24(0, &month, &day, &hours, &minutes, &seconds);
//	  weekday=AB0805_getDayOfWeek();
//	  LCD_BMP("0:dzien.bmp");
//	  taskEXIT_CRITICAL();
		  taskENTER_CRITICAL();
		  AB0805_getDateTime24(0, &month, &day, &hours, &minutes, &seconds);
		  weekday=AB0805_getDayOfWeek();
		  LCD_BMP("0:dzien.bmp");
		taskEXIT_CRITICAL();
	  break;
  }
  case WM_INIT_DIALOG:
  {
	  taskENTER_CRITICAL();
	  if(AB0805_getMinutes()==AB0805_getMinutes_Alarm() &&  AB0805_getHours24()==AB0805_getHours24_Alarm())
	  {
		  while(!GUI_PID_IsPressed() && sec2<4000)
		  {
			  LED_ON;
			  delay(500);
			  LED_OFF;
			  delay(300);
			  IWDG_ReloadCounter();
		  }
	  }
	  taskEXIT_CRITICAL();
	  jed=1;

    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_TRANSPARENT);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
//    TEXT_SetFont(hItem, &GUI_FontStencil118);
    TEXT_SetFont(hItem, &GUI_FontSolidEdgeStencil118);
    TEXT_SetText(hItem, "");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "");
    TEXT_SetFont(hItem, &GUI_FontSolidEdgeStencil118);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, ":");
    TEXT_SetFont(hItem, &GUI_FontSolidEdgeStencil118);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetText(hItem, "");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);    // seconds
    TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
    TEXT_SetText(hItem, "");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetText(hItem, "");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetText(hItem, "");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetText(hItem, "");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetText(hItem, "");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetText(hItem, "");


    u8 dzien;
    char number[2];

	  taskENTER_CRITICAL();
	  AB0805_getDateTime24(0, &month, &day, &hours, &minutes, &seconds);
	  weekday=AB0805_getDayOfWeek();
	  taskEXIT_CRITICAL();

	WM_HWIN minute = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	sprintf(number,"%0.2d",minutes);
	TEXT_SetText(minute,number);
	TEXT_SetTextColor(minute,col_gui);
//	TEXT_SetTextColor(minute,GUI_WHITE);
	WM_HWIN hour = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	sprintf(number,"%0.2d",hours);
	TEXT_SetText(hour,number);
	TEXT_SetTextColor(hour,col_gui);
//	TEXT_SetTextColor(hour,GUI_WHITE);

	hour = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
	TEXT_SetText(hour,seconds);
	TEXT_SetTextColor(hour,col_gui);

    break;
  }
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

static void _cbDummy(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  FIL fsrc;
  RTC_DateTypeDef datea;

  switch (pMsg->MsgId)
  {
  case WM_INIT_DIALOG:

	  taskENTER_CRITICAL();
	  weekday=AB0805_getDayOfWeek();
	  taskEXIT_CRITICAL();

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "");
    switch(weekday)
	{
		case 1:
		{
			TEXT_SetText(hItem,"Monday");
			break;
		}
		case 2:
		{
			TEXT_SetText(hItem,"Tuesday");
			break;
		}
		case 3:
		{
			TEXT_SetText(hItem,"Wednesday");
			break;
		}
		case 4:
		{
			TEXT_SetText(hItem,"Thursday");
			break;
		}
		case 5:
		{
			TEXT_SetText(hItem,"Friday");
			break;
		}
		case 6:
		{
			TEXT_SetText(hItem,"Saturday");
			break;
		}
		case 7:
		{
			TEXT_SetText(hItem,"Sunday");
			break;
		}
	}
    //
    // Initialization of 'plan'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
//    TEXT_SetText(hItem, "");

    taskENTER_CRITICAL();

	switch(weekday)
			{
				case 1:
				{
					f_open(&fsrc,"0:plan/pon.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 2:
				{
					f_open(&fsrc,"0:plan/wt.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 3:
				{
					f_open(&fsrc,"0:plan/sr.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 4:
				{
					f_open(&fsrc,"0:plan/czw.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 5:
				{
					f_open(&fsrc,"0:plan/pt.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 6:
				{
					f_open(&fsrc,"0:plan/so.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 7:
				{
					f_open(&fsrc,"0:plan/nie.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
			}
//	f_open(&fsrc,"0:plan/pon.txt",FA_OPEN_EXISTING|FA_READ);
//	u8 aucc[f_size(&fsrc)];
	f_read(&fsrc,auc,f_size(&fsrc),&kk);
	TEXT_SetText(hItem, auc);
	taskEXIT_CRITICAL();

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    TEXT_SetText(hItem, "");
    //
    // Initialization of 'do'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    TEXT_SetText(hItem, "");
    //
    // Initialization of 'OD'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    //
    // Initialization of 'DO'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_PAINT:
  {
	  taskENTER_CRITICAL();
	  AB0805_getDateTime24(0, &month, &day, &hours, &minutes, &seconds);
	  weekday=AB0805_getDayOfWeek();
	  LCD_BMP("0:dzien.bmp");
	taskEXIT_CRITICAL();
	  break;
  }
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

WM_HWIN Createplan(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate2, GUI_COUNTOF(_aDialogCreate2), _cbDummy, WM_HBKWIN, 0, 0);
  return hWin;
}

WM_HWIN Createclock(void)
{
  WM_HWIN hWin1,hWinBase;
  hWin1 = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_CF_SHOW, 0, 0);
  return hWin1;
}

void Clock( void * pvParameters)
{

	long int z=0;
	WM_HWIN hWinplan=0,hWinBase;
	GUI_PID_STATE stat;
	hWinclock = Createclock();
	FRESULT f=0;
	FIL fsrc;
	FATFS fs;
	int tre=0;
	u16 data[6];
	u8 dzien=1;
	if(Menu_Handle!=NULL)vTaskDelete(Menu_Handle);
	Menu_Handle=NULL;

	while(1)
	{
		if(GUI_PID_IsPressed() && hWinplan==0)
		{
//			if(sec2>400)
//			{
////				hWinplan=Createplan();
//				xTaskCreate(Menu,(char const*)"Menu",512,NULL,6,&Menu_Handle);

//			}
		}
		else
		{
			sec2=0;
		}
		if(wake)
		{
			  while(1){CPU_OFF;}
		}
		else
		{
			  CPU_ON;
		}

		if(vol_up)
		{
//			WM_HWIN hFrame = FRAMEWIN_CreateEx(0, 0, 320, 240, WM_HBKWIN, WM_CF_HIDE, 0, 0, "Notepad", 0);
//			GUI_MEMDEV_ShiftInWindow(hWinclock,500,GUI_MEMDEV_EDGE_LEFT);
//			WM_MOTION_SetMovement(hWinclock,GUI_COORD_X,240,240);
//			hWinViewport = WM_CreateWindow(0, 0, 320, 240 ,WM_HBKWIN, _cbDummy, 0);
//			hWinplan=Createplan();
//			hWinplan=CreateAlarm();
		}
		else if(vol_down)
		{
			USART_puts("TTM:RST-SYSTEMRESET");
			MPU6050_WriteBit(MPU6050_RA_INT_PIN_CFG , 7, 1);
			hWinplan=Createplan();
		}

		char number[3];
		  taskENTER_CRITICAL();
		  AB0805_getDateTime24(0, &month, &day, &hours, &minutes, &seconds);
		  weekday=AB0805_getDayOfWeek();
		  taskEXIT_CRITICAL();
//		  hours = seconds;
		WM_HWIN sec = WM_GetDialogItem(hWinclock, ID_TEXT_5);
		sprintf(number,"%0.2d",seconds);
		TEXT_SetText(sec,number);
		TEXT_SetTextColor(sec,col_gui);
		WM_HWIN date = WM_GetDialogItem(hWinclock, ID_TEXT_4);
		sprintf(number,"%0.2d",day );
		strcat(number,".");
		TEXT_SetText(date,number);
		WM_HWIN mont = WM_GetDialogItem(hWinclock, ID_TEXT_7);
		sprintf(number,"%0.2d", month);
		TEXT_SetTextColor(mont,col_gui);
		TEXT_SetText(mont,number);
		TEXT_SetTextColor(date,col_gui);
		WM_HWIN weekd = WM_GetDialogItem(hWinclock, ID_TEXT_3);
		TEXT_SetTextColor(weekd,col_gui);
		switch(weekday)
		{
			case 1:
			{
				TEXT_SetText(weekd,"Monday");
				break;
			}
			case 2:
			{
				TEXT_SetText(weekd,"Tuesday");
				break;
			}
			case 3:
			{
				TEXT_SetText(weekd,"Wednesday");
				break;
			}
			case 4:
			{
				TEXT_SetText(weekd,"Thursday");
				break;
			}
			case 5:
			{
				TEXT_SetText(weekd,"Friday");
				break;
			}
			case 6:
			{
				TEXT_SetText(weekd,"Saturday");
				break;
			}
			case 7:
			{
				TEXT_SetText(weekd,"Sunday");
				break;
			}
		}

		WM_HWIN minute = WM_GetDialogItem(hWinclock, ID_TEXT_1);
		sprintf(number,"%0.2d",minutes);
		TEXT_SetText(minute,number);
		TEXT_SetTextColor(minute,col_gui);
		WM_HWIN hour = WM_GetDialogItem(hWinclock, ID_TEXT_0);
		sprintf(number,"%0.2d",hours);
		TEXT_SetText(hour,number);
		TEXT_SetTextColor(hour,col_gui);
		WM_HWIN dwu = WM_GetDialogItem(hWinclock, ID_TEXT_2);
		if(seconds%2==0)TEXT_SetText(dwu,"");
		else TEXT_SetText(dwu,":");
		TEXT_SetTextColor(dwu,col_gui);
		WM_HWIN till = WM_GetDialogItem(hWinclock, ID_TEXT_6);
		TEXT_SetTextColor(till,col_gui);

		char lekcja='-';

		if((hours<8)||(hours==8 && minutes<=15))
		{
			TEXT_SetText(till,"8:15");
			lekcja='1';
		}
		else if((hours==8 && minutes>15) || (hours==9 && minutes==0))
		{
			TEXT_SetText(till,"9:00");
			lekcja='2';
		}
		else if(hours==9 && minutes<=10)
		{
			TEXT_SetText(till,"9:10");
			lekcja='2';
		}
		else if(hours==9 && minutes<=55)
		{
			TEXT_SetText(till,"9:55");
			lekcja='3';
		}
		else if((hours==10 && minutes<=5)||(hours==9 && minutes>55))
		{
			TEXT_SetText(till,"10:05");
			lekcja='3';
		}
		else if(hours==10 && minutes<=50)
		{
			TEXT_SetText(till,"10:50");
			lekcja='4';
		}
		else if((hours==11 && minutes<=10) || (hours==10 && minutes>50))
		{
			TEXT_SetText(till,"11:10");
			lekcja='4';
		}
		else if(hours==11 && minutes<=50)
		{
			TEXT_SetText(till,"11:55");
			lekcja='5';
		}
		else if((hours==12 && minutes<=5) || (hours==11 && minutes>50))
		{
			TEXT_SetText(till,"12:05");
			lekcja='5';
		}
		else if(hours==12 && minutes<=50)
		{
			TEXT_SetText(till,"12:50");
			lekcja='6';
		}
		else if((hours==12 && minutes>50)||(hours==13 && minutes==0))
		{
			TEXT_SetText(till,"13:00");
			lekcja='6';
		}
		else if(hours==13 && minutes<=45)
		{
			TEXT_SetText(till,"13:45");
			lekcja='7';
		}
		else if(hours==13 && minutes<=55)
		{
			TEXT_SetText(till,"13:55");
			lekcja='7';
		}
		else if((hours==13 && minutes>55) || (hours==14 && minutes<=40))
		{
			TEXT_SetText(till,"14:40");
			lekcja='8';
		}
		else if(hours==14 && minutes<=50)
		{
			TEXT_SetText(till,"14:50");
			lekcja='8';
		}
		else if((hours==14 && minutes>50)||(hours==15 && minutes<=35))
		{
			TEXT_SetText(till,"15:35");
			lekcja='9';
		}
		else
		{
			TEXT_SetText(till,"--:--");
		}

		if(jed && lekcja!='-')
		{

			taskENTER_CRITICAL();
			switch(weekday)
			{
				case 1:
				{
					f_open(&fsrc,"0:plan/pon.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 2:
				{
					f_open(&fsrc,"0:plan/wt.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 3:
				{
					f_open(&fsrc,"0:plan/sr.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 4:
				{
					f_open(&fsrc,"0:plan/czw.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 5:
				{
					f_open(&fsrc,"0:plan/pt.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 6:
				{
					f_open(&fsrc,"0:plan/so.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
				case 7:
				{
					f_open(&fsrc,"0:plan/nie.txt",FA_OPEN_EXISTING|FA_READ);
					break;
				}
			}
			char aucc[f_size(&fsrc)];
			f_read(&fsrc,aucc,f_size(&fsrc),&kk);
//			GUI_DispDecAt(sizeof(&fsrc),220,220,5);

			int i=0;
			while(aucc[i]!=lekcja || aucc[i+1]!='.')
			{
				i++;
				if(i>=f_size(&fsrc))break;
			}
			WM_HWIN lesson = WM_GetDialogItem(hWinclock, ID_TEXT_8);
			TEXT_SetTextColor(lesson,col_gui);
			u8 lk=0;
			char less[20];
			while(aucc[i]!='\n')
			{
				less[lk++]=aucc[i++];
			}
			TEXT_SetText(lesson,less);
			jed=0;
			taskEXIT_CRITICAL();
		}

		WM_HWIN bat = WM_GetDialogItem(hWinclock, ID_TEXT_5);
		TEXT_SetTextColor(bat,col_gui);
		vTaskDelay(50);
	}
}

//			jpeg_create_decompress(&cinfo);
//			cinfo.err = jpeg_std_error(&jerr);
//		    f=f_open(&fsrc,"0:papiez.jpg", FA_READ | FA_OPEN_EXISTING );
//		    jpeg_decode(&fsrc, 320, auc, 0);
//		    jpeg_finish_decompress(&cinfo);
//		    jpeg_destroy_decompress(&cinfo);






